### ISSUE TITLE
What is the block device?

### ISSUE THREAD

**Issue by Fuzzo** [thopiekar/rcraid-dkms#17] opened 2020-03-17 08:46 UTC
Hi and first of all thank you for your work.
I've an X570 based motherboard with 2*TB NVME SSD configured in Raid 0.
Now i'm running Windows without any problem. 
I'm evaluating to install Linux in dual boot on my system, but first of all, i tried the rcraid drivers with a live Linux Mint 19.2 (kernel 4.15, Ubuntu based).
What I did:
- booted from live usb
- installed rcraid package using the PPA
- unloaded ahci kernel module
- loaded the rcraid kernel module
I can see on dmesg  the module is loaded (even if on a "tainting kernel") but I expect that, in the same way it happens on Windows when the drivers are loaded, a new block device (like AMD-RAID on Windows) becomes available instead of the 2 separated drives.
I also have the /proc/scsi/rcraid directory available so I suppose the module is loaded...
What is the device that the module should provide?
Thanks

**Comment by kubuntugamer** [comment] 2020-07-30 02:58
nvme raid is not supported by this driver

**Comment by thopiekar** [comment] 2020-10-31 19:12
See the same issue here after buying one NVMe recently. I expected it to pop up as a LEGACY drive as it would happen for any other SATA-based drive. However, I see the same behavior on Windows, so I won't blame it on the Linux drivers directly.

This issue is a duplicate of #25. Let's continue discussing there.

**Closed by thopiekar** 2020-10-31 19:12 UTC
